# @package paths
style_path: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/activation_matters/plots"
trained_RNNs_path: "/Users/tolmach/Documents/GitHub/trainRNNbrain/data/trained_RNNs"
RNN_dataset_path: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/RNN_datasets"
LC_dataset_path: "/Users/tolmach/Documents/GitHub/latent_circuit_inference/data/inferred_LCs"

auxilliary_datasets_path: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/auxilliary_datasets"
img_folder: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/img"
feature_datasets_folder: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/feature_datasets"
fixed_points_data_folder: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/fixed_points"