# @package task
paths:
  style_path: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN"
  trained_RNNs_path: "/Users/tolmach/Documents/GitHub/trainRNNbrain/data/trained_RNNs"
  RNN_dataset_path: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/RNN_datasets"
#  LC_dataset_path: "/Users/tolmach/Documents/GitHub/latent_circuit_inference/data/inferred_LCs"
  LC_dataset_path: "/Users/tolmach/Documents/GitHub/latent_circuit_inference/data/inferred_LCs"
  auxilliary_datasets_path: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/auxilliary_datasets/CDDM"
  img_folder: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/img/CDDM"
  feature_datasets_folder: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/feature_datasets/CDDM"
  fixed_points_data_folder: "/Users/tolmach/Documents/GitHub/ActivationMattersRNN/data/fixed_points/CDDM"

taskname : 'CDDM'
dt: 1
tau: 10
_target_: "trainRNNbrain.tasks.TaskCDDM.TaskCDDM"
T: 300
seed: null
T_cue_on: 0
T_cue_off: 300
T_stim_on: 100
T_stim_off: 300
T_dec_on: 200
T_dec_off: 300
n_inputs: 6
n_outputs: 2
coherences: [-0.8, -0.4, -0.1, 0, 0.1, 0.4, 0.8]
task_params: ["n_steps",
              "n_inputs", "n_outputs",
              "cue_on", "cue_off", "stim_on", "stim_off", "dec_on", "dec_off",
              "coherences"]

dataset_filtering_params:
  relu_filters:
    activation_slope: 1
    mfr_thr: 0.02
    std_thr: 0.02
    RNN_score_filter: 0.01
    constrained: True
    lambda_r: 0.3
    n_steps: 300

  tanh_filters:
    activation_slope: 1
    mfr_thr: 0.02
    std_thr: 0.02
    RNN_score_filter: 0.025
    constrained: True
    lambda_r: 0.3
    n_steps: 300

  sigmoid_filters:
    activation_slope: 7.5
    mfr_thr: 0.02
    std_thr: 0.02
    RNN_score_filter: 0.01
    constrained: True
    lambda_r: 0.3
    n_steps: 300

trajectory_analysis_params:
  n_PCs: 10
  n_nets: 30
  distance_metric: "MSE"
  dist_mat_plot_lower_bound: 0.0
  save_figures: True
  coherences: [-1, -0.5, 0, 0.5, 1.0]
  trajectory_plot_params: null

neurreps_analysis_params:
  n_PCs: 10

stimreps_analysis_params:
  n_PCs: 10
  coherences: [-1, -0.5, 0, 0.5, 1.0]

dynamical_topology_analysis:
  n_PCs: 7
  fp_search_params:
    fun_tol: 1e-4
    diff_cutoff: 1e-1
    sigma_init_guess: 0.01
    patience: 100
    stop_length: 50
    mode: "exact"
  inputs:
    - [ 1.0, 0.0, 0.0, 1.0, 0.0, 1.0 ] # 1
    - [ 1.0, 0.0, 0.0, 1.0, 0.25, 0.75 ] #2
    - [ 1.0, 0.0, 0.0, 1.0, 0.5, 0.5 ]     #3
    - [ 1.0, 0.0, 0.0, 1.0, 0.75, 0.25 ]     #4
    - [ 1.0, 0.0, 0.0, 1.0, 1.0, 0.0 ] #5
    - [ 1.0, 0.0, 0.25, 0.75, 0.0, 1.0 ] # 6
    - [ 1.0, 0.0, 0.25, 0.75, 0.25, 0.75 ] #7
    - [ 1.0, 0.0, 0.25, 0.75, 0.5, 0.5 ]     #8
    - [ 1.0, 0.0, 0.25, 0.75, 0.75, 0.25 ]  #9
    - [ 1.0, 0.0, 0.25, 0.75, 1.0, 0.0 ]      #10
    - [ 1.0, 0.0, 0.5, 0.5, 0.0, 1.0 ] # 11
    - [ 1.0, 0.0, 0.5, 0.5, 0.25, 0.75 ] #12
    - [ 1.0, 0.0, 0.5, 0.5, 0.5, 0.5 ]      #13
    - [ 1.0, 0.0, 0.5, 0.5, 0.75, 0.25 ]      #14
    - [ 1.0, 0.0, 0.5, 0.5, 1.0, 0.0 ]  #15
    - [ 1.0, 0.0, 0.75, 0.25, 0.0, 1.0 ]    #16
    - [ 1.0, 0.0, 0.75, 0.25, 0.25, 0.75 ] #17
    - [ 1.0, 0.0, 0.75, 0.25, 0.5, 0.5 ] #18
    - [ 1.0, 0.0, 0.75, 0.25, 0.75, 0.25 ]  #19
    - [ 1.0, 0.0, 0.75, 0.25, 1.0, 0.0 ]      #20
    - [ 1.0, 0.0, 1.0, 0.0, 0.0, 1.0 ]    #21
    - [ 1.0, 0.0, 1.0, 0.0, 0.25, 0.75 ] #22
    - [ 1.0, 0.0, 1.0, 0.0, 0.5, 0.5 ] #23
    - [ 1.0, 0.0, 1.0, 0.0, 0.75, 0.25 ]  #24
    - [ 1.0, 0.0, 1.0, 0.0, 1.0, 0.0 ]      #25
    - [ 0.0, 1.0, 0.0, 1.0, 0.0, 1.0 ] # 1
    - [ 0.0, 1.0, 0.25, 0.75, 0.0, 1.0 ] #2
    - [ 0.0, 1.0, 0.5, 0.5, 0.0, 1.0 ]     #3
    - [ 0.0, 1.0, 0.75, 0.25, 0.0, 1.0 ]     #4
    - [ 0.0, 1.0, 1.0, 0.0, 0.0, 1.0 ] #5
    - [ 0.0, 1.0, 0.0, 1.0, 0.25, 0.75] # 6
    - [ 0.0, 1.0, 0.25, 0.75, 0.25, 0.75 ] #7
    - [ 0.0, 1.0, 0.5, 0.5, 0.25, 0.75]     #8
    - [ 0.0, 1.0, 0.75, 0.25, 0.25, 0.75]  #9
    - [ 0.0, 1.0, 1.0, 0.0, 0.25, 0.75]      #10
    - [ 0.0, 1.0, 0.0, 1.0, 0.5, 0.5] # 11
    - [ 0.0, 1.0, 0.25, 0.75, 0.5, 0.5 ] #12
    - [ 0.0, 1.0, 0.5, 0.5, 0.5, 0.5 ]      #13
    - [ 0.0, 1.0, 0.75, 0.25, 0.5, 0.5 ]      #14
    - [ 0.0, 1.0, 1.0, 0.0, 0.5, 0.5 ]  #15
    - [ 0.0, 1.0, 0.0, 1.0, 0.75, 0.25 ]    #16
    - [ 0.0, 1.0, 0.25, 0.75, 0.75, 0.25 ] #17
    - [ 0.0, 1.0, 0.5, 0.5, 0.75, 0.25 ] #18
    - [ 0.0, 1.0, 0.75, 0.25, 0.75, 0.25 ]  #19
    - [ 0.0, 1.0, 1.0, 0.0, 0.75, 0.25 ]      #20
    - [ 0.0, 1.0, 0.0, 1.0, 1.0, 0.0]    #21
    - [ 0.0, 1.0, 0.25, 0.75, 1.0, 0.0] #22
    - [ 0.0, 1.0, 0.5, 0.5, 1.0, 0.0 ] #23
    - [ 0.0, 1.0, 0.75, 0.25, 1.0, 0.0 ]  #24
    - [ 0.0, 1.0, 1.0, 0.0, 1.0, 0.0 ]      #25
  colors: #
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
  edgecolors:
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
    - [[0.3, 0.4, 0.8], [0.3, 0.4, 0.8]]
    - [[0.55, 0.7, 0.9], [0.55, 0.7, 0.9]]
    - [[0.8, 0.8, 0.8], [0.8, 0.8, 0.8]]
    - [[0.9, 0.6, 0.6], [0.9, 0.6, 0.6]]
    - [[0.8, 0.2, 0.3], [0.8, 0.2, 0.3]]
  markers:
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["o", "*"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]
    - ["p", "X"]

feature_extraction_params:
  downsample_window: 10
  Trajectory:
    "zscore": True
    "normalize": False
    "do_pca": True
    "var_thr": 0.99
  "Connectivity":
    "zscore": True
    "normalize": False
    "do_pca": True
    "var_thr": 0.99

#DSA_params:
#  n_nets: 10
#  n_delays: 50
#  rank: 30

#representations_analysis:
#  max_iter: 20
#  gamma: 0.2
#  increase_gamma: False
#  cluster_scoring_method: "DaviesBouldin"
#  selection_criteria: "knee"
#  min_clusters: 6
#  max_clusters: 20
#  n_repeats: 5
#  thr: 0.15
#  tanh_nets:
#    connectivity_importance_factor: 1
#    nrn_type_importance_factor: 0.5
#  relu_nets:
#    connectivity_importance_factor: 1
#    nrn_type_importance_factor: 0.5
#  sigmoid_nets:
#    connectivity_importance_factor: 1
#    nrn_type_importance_factor: 0.5
#  save_figures: True
#  show_figures: False







